# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xzaiF207tSreSDBJFwRL0sN1eHIvTRMj

### Dataset Description

* **Where the dataset comes from:**  
  The dataset contains official historical match records of the English Premier League (EPL) spanning from the 1993–1994 season up to recent seasons, sourced from open sports repositories such as Kaggle and football-data.co.uk.

* **Why it was collected:**  
  It was collected to maintain a comprehensive historical archive of professional league results, track club performance over time, study match outcomes, and support statistical and sports analytics modeling.

* **Who collected it:**  
  The data was originally logged by match officials and curated by sports data aggregators and open-source contributors (such as Joseph Buchdahl via football-data.co.uk and Kaggle contributors).

* **What each feature represents:**  
  * `Season`: The competitive league season during which the fixture occurred (e.g., 1993-94).
  * `DateTime`: The specific date and kickoff timestamp of the match.
  * `HomeTeam`: The club playing at their home venue.
  * `AwayTeam`: The visiting club.
  * `FTHG` (Full Time Home Goals): The number of goals scored by the home team.
  * `FTAG` (Full Time Away Goals): The number of goals scored by the away team.
  * `FTR` (Full Time Result): The match outcome classification (`H` = Home win, `D` = Draw, `A` = Away win).

* **Possible limitations or biases in the data:**  
  * **Lack of In-Game Tactical Context:** The raw data records only final score tallies, omitting crucial match variables such as total shots, possession, fouls, and injuries.
  * **Systemic Home Advantage Bias:** In football, home teams historically possess an intrinsic scoring and winning advantage, skewing symmetry in scoreline distributions.
  * **Temporal / Tactical Drift:** Over the span of nearly 30 years, shifts in tactical styles, league rules, and financial disparity between clubs mean that match dynamics in the early 1990s differ substantially from modern seasons.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv("results.csv")
df["DateTime"] = pd.to_datetime(df["DateTime"], errors="coerce")

df["TotalGoals"] = df["FTHG"] + df["FTAG"]
df["GoalDifference"] = df["FTHG"] - df["FTAG"]
df["AbsGoalMargin"] = (df["FTHG"] - df["FTAG"]).abs()
df["HomeWin"] = (df["FTR"] == "H").astype(int)
df["AwayWin"] = (df["FTR"] == "A").astype(int)
df["MatchMonth"] = df["DateTime"].dt.month

feature_cols = [
    "FTHG",
    "FTAG",
    "TotalGoals",
    "GoalDifference",
    "AbsGoalMargin",
    "HomeWin",
    "AwayWin",
    "MatchMonth",
]

print("--- Structural Analysis ---")
print(f"Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns")
print("\nData Types:")
print(df[feature_cols].dtypes)
print("\nMissing Values:")
print(df[feature_cols].isnull().sum())
print("\nStatistical Summary:")
print(df[feature_cols].describe().round(3))

plt.figure(figsize=(8, 6))
sns.heatmap(
    df[feature_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5
)
plt.title("Correlation Matrix of Features")
plt.tight_layout()
plt.show()

numeric_metrics = [
    "FTHG",
    "FTAG",
    "TotalGoals",
    "GoalDifference",
    "AbsGoalMargin",
]
fig, axes = plt.subplots(len(numeric_metrics), 2, figsize=(12, 14))

for i, col in enumerate(numeric_metrics):
    sns.histplot(
        df[col], kde=True, discrete=True, ax=axes[i, 0], color="royalblue"
    )
    axes[i, 0].set_title(
        f"{col} - Distribution (Skew: {df[col].skew():.2f}, Kurt: {df[col].kurtosis():.2f})"
    )

    sns.boxplot(x=df[col], ax=axes[i, 1], color="coral")
    axes[i, 1].set_title(f"{col} - Boxplot")

plt.tight_layout()
plt.show()

skew_kurt_df = pd.DataFrame(
    {"Skewness": df[feature_cols].skew(), "Kurtosis": df[feature_cols].kurtosis()}
).round(3)
print("\nSkewness and Kurtosis Summary:")
print(skew_kurt_df)

"""# Section 2: Exploratory Data Analysis (EDA)

### 1. Structural Findings
* **Dataset Shape:** 11,113 observations and 8 numerical features utilized for unsupervised pipeline modeling.
* **Missingness & Integrity:** 0 missing values detected across all analyzed match features.
* **Correlations:**
  * Expected mathematical coupling between `FTHG`/`FTAG` and `TotalGoals` (r = 0.69 and 0.61 respectively).
  * Direct alignment between `GoalDifference` and match outcome flags (`HomeWin`: r = 0.77, `AwayWin`: r = -0.73).
  * Moderate independent variation across temporal variables (`MatchMonth`) ensures multi-faceted structure.

---

### 2. Distribution Analysis
* **FTHG & FTAG (Home/Away Goals):**
  * Both features display right-skewed distributions (`Skewness`: +1.00 for Home, +1.09 for Away) characteristic of Poisson count processes.
  * Positive kurtosis (+1.37 and +1.40) demonstrates acute peaking around modal outcomes (1–2 goals) with extended right-hand tails.
* **TotalGoals & AbsGoalMargin:**
  * `TotalGoals` centers at an average of 2.66 goals per match with a right-skew of +0.63.
  * `AbsGoalMargin` has a positive skew (+1.18) and kurtosis (+2.00), showing that most fixtures end in tight results (margins of 0, 1, or 2 goals), while blowouts represent a distinct tail.
* **GoalDifference:**
  * Near-symmetric distribution (`Skewness`: +0.07) centered slightly above zero (mean = +0.38), mathematically confirming systemic home advantage.

---

### 3. Outlier Exploration & Data Integrity
* **Heavy Tails & Extreme Values:**
  * Severe outliers exist at the upper score margins (e.g., maximum scorelines of 9 goals scored by a single team, and total match goals reaching 11).
  * Rather than synthetic noise or errors, these tail events correspond to verified historical EPL occurrences (such as Manchester United 9–0 Ipswich in 1995, Southampton 0–9 Leicester in 2019, and Portsmouth 7–4 Reading in 2007).
* **Noise vs. Genuine Variance:**
  * The dataset exhibits virtually zero sensor-like noise. Variance originates strictly from intrinsic sporting randomness (red cards, penalty decisions, tactical implosions).
* **Measurement Artifacts & Data-Entry Problems:**
  * All goal counts fall strictly within valid non-negative integer domains ($x \in \mathbb{N}_0$).
  * Temporal sanity checks confirm dates and seasonal codes follow sequential scheduling patterns without corruption or unformatted entry artifacts.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

feature_cols = [
    "FTHG",
    "FTAG",
    "TotalGoals",
    "GoalDifference",
    "AbsGoalMargin",
    "HomeWin",
    "AwayWin",
    "MatchMonth",
]
X = df[feature_cols]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA()
X_pca = pca.fit_transform(X_scaled)

explained_var = pca.explained_variance_ratio_
cum_var = np.cumsum(explained_var)

var_df = pd.DataFrame(
    {
        "Component": [f"PC{i+1}" for i in range(len(feature_cols))],
        "Explained_Variance": np.round(explained_var, 4),
        "Cumulative_Variance": np.round(cum_var, 4),
    }
)
print("--- Variance Explained Summary ---")
print(var_df.to_string(index=False))

fig, ax1 = plt.subplots(figsize=(8, 4.5))
ax1.bar(
    range(1, len(explained_var) + 1),
    explained_var,
    alpha=0.7,
    color="steelblue",
    label="Individual Explained Variance",
)
ax1.set_ylabel("Variance Ratio", color="steelblue")
ax1.set_xlabel("Principal Component Index")
ax1.set_xticks(range(1, len(explained_var) + 1))

ax2 = ax1.twinx()
ax2.plot(
    range(1, len(cum_var) + 1),
    cum_var,
    color="darkred",
    marker="o",
    linewidth=2,
    label="Cumulative Explained Variance",
)
ax2.axhline(
    y=0.85, color="grey", linestyle="--", alpha=0.7, label="85% Threshold"
)
ax2.set_ylabel("Cumulative Ratio", color="darkred")

plt.title("Scree Plot & Cumulative Explained Variance")
fig.tight_layout()
plt.show()

outcome_labels = df["FTR"].map(
    {"H": "Home Win", "D": "Draw", "A": "Away Win"}
)

plt.figure(figsize=(8, 5))
for outcome, color in zip(
    ["Home Win", "Draw", "Away Win"], ["royalblue", "gray", "crimson"]
):
    idx = outcome_labels == outcome
    plt.scatter(
        X_pca[idx, 0],
        X_pca[idx, 1],
        c=color,
        label=outcome,
        alpha=0.3,
        edgecolors="none",
        s=18,
    )
plt.xlabel(f"PC1 ({explained_var[0]*100:.1f}%) - Match Dominance / Outcome")
plt.ylabel(f"PC2 ({explained_var[1]*100:.1f}%) - Goal Volume / Intensity")
plt.title("2D PCA Projection")
plt.legend()
plt.grid(True, linestyle=":", alpha=0.5)
plt.tight_layout()
plt.show()

fig = plt.figure(figsize=(9, 6))
ax = fig.add_subplot(111, projection="3d")
for outcome, color in zip(
    ["Home Win", "Draw", "Away Win"], ["royalblue", "gray", "crimson"]
):
    idx = outcome_labels == outcome
    ax.scatter(
        X_pca[idx, 0],
        X_pca[idx, 1],
        X_pca[idx, 2],
        c=color,
        label=outcome,
        alpha=0.25,
        s=15,
    )
ax.set_xlabel(f"PC1 ({explained_var[0]*100:.1f}%)")
ax.set_ylabel(f"PC2 ({explained_var[1]*100:.1f}%)")
ax.set_zlabel(f"PC3 ({explained_var[2]*100:.1f}%)")
ax.set_title("3D PCA Projection")
plt.legend()
plt.tight_layout()
plt.show()

loadings = pd.DataFrame(
    pca.components_.T,
    index=feature_cols,
    columns=[f"PC{i+1}" for i in range(len(feature_cols))],
)
print("\n--- Loadings (First 3 Components) ---")
print(loadings.iloc[:, :3].round(3))

"""# Section 3: Dimensionality Reduction — 3.1 Principal Component Analysis (PCA)

### Numerical & Variance Findings
* **PC1:** Explains **43.53%** of total variance.
* **PC2:** Explains **28.66%** of total variance.
* **PC3:** Explains **12.51%** of total variance.
* **PC4:** Explains **9.96%** of total variance.
* The first 3 components account for **84.70%** of total variance, and the first 4 components capture **94.67%**.

---

### Discussion & Question Responses

* **How many principal components are needed to adequately represent the data?**  
  **3 components** are sufficient to capture the vast majority of the data's geometry (**84.70%** of variance). Adding a 4th component raises the captured variance to nearly **95%**, capturing virtually all remaining meaningful signals before hitting numerical noise.

* **How much information is lost when reducing the dimensionality?**  
  * Reducing to **2D** retains **72.19%** of variance (**27.81% loss**), mainly omitting calendar seasonality.  
  * Reducing to **3D** retains **84.70%** of variance (**15.30% loss**).  
  * Reducing from 8 features to 4 components retains **94.67%**, meaning only **5.33%** of information is discarded. The last two eigenvalues are strictly 0.00 due to exact mathematical collinearity (`TotalGoals = FTHG + FTAG`).

* **Which variables are strongly correlated, and how does this affect PCA?**  
  * `TotalGoals` is an exact linear combination of `FTHG` and `FTAG`, and `GoalDifference` linearly combines them. Additionally, outcome indicators (`HomeWin`, `AwayWin`) correlate heavily with goal margins.  
  * **Effect:** Strong multicollinearity causes variance to concentrate heavily in the first few eigenvectors, rendering the last two components redundant ($0\%$ variance).

* **Interpretation of Major Components (Feature Loadings):**  
  * **PC1 (Match Outcome & Dominance):** Heavy positive loadings on `GoalDifference` (+0.517), `HomeWin` (+0.471), and `FTHG` (+0.444), with negative loading on `AwayWin` (-0.403). It separates home blowout victories from away wins.
  * **PC2 (Match Scoring Volume & Intensity):** High positive loadings on `TotalGoals` (+0.601), `FTAG` (+0.514), `AbsGoalMargin` (+0.425), and `FTHG` (+0.327). It distinguishes low-scoring draws from high-scoring, chaotic fixtures.
  * **PC3 (Temporal Variation):** Dominated almost entirely by `MatchMonth` (-0.997), capturing calendar and scheduling distribution independent of match events.

* **Does the reduced dataset provide a more effective representation?**  
  **Yes.** The original 8-dimensional space contained substantial redundancy (linear dependencies between scorelines, margins, and outcome flags). Projecting onto the first 3 orthogonal axes strips away collinear artifacts, presenting an uncorrelated, clean representation of match outcomes and goal intensities.

---

### Critical Dimensions Comparison

* **Local vs. Global Structure:** PCA preserves global linear variance across the full distribution, separating extreme home/away wins at opposite poles, but can compress finer local sub-patterns among closely contested draws.
* **Cluster Separation:** In the 2D projection, draws (`D`) form a dense cluster near the origin, whereas home wins (`H`) and away wins (`A`) fan out along the positive and negative ends of PC1.
* **Stability:** PCA is globally stable on large datasets ($N = 11,113$), though sensitive to extreme scoring blowouts (e.g., 9–0 games) which exert high leverage on the orientation of PC1 and PC2.
* **Computational Cost:** Negligible. Computing the singular value decomposition (SVD) on an $11113 \times 8$ matrix takes less than 50 milliseconds.
* **Interpretability:** Highly intuitive: PC1 represents *Goal Margin/Dominance*, PC2 represents *Total Match Volume*, and PC3 reflects *Seasonal Timing*.
* **Redundancy:** The original matrix possessed at least 2 zero-variance null dimensions due to deterministic linear dependencies; PCA efficiently eliminates this rank deficiency.# Section 3: Dimensionality Reduction — 3.1 Principal Component Analysis (PCA)

### Numerical & Variance Findings
* **PC1:** Explains **43.53%** of total variance.
* **PC2:** Explains **28.66%** of total variance.
* **PC3:** Explains **12.51%** of total variance.
* **PC4:** Explains **9.96%** of total variance.
* The first 3 components account for **84.70%** of total variance, and the first 4 components capture **94.67%**.

---

### Discussion & Question Responses

* **How many principal components are needed to adequately represent the data?**  
  **3 components** are sufficient to capture the vast majority of the data's geometry (**84.70%** of variance). Adding a 4th component raises the captured variance to nearly **95%**, capturing virtually all remaining meaningful signals before hitting numerical noise.

* **How much information is lost when reducing the dimensionality?**  
  * Reducing to **2D** retains **72.19%** of variance (**27.81% loss**), mainly omitting calendar seasonality.  
  * Reducing to **3D** retains **84.70%** of variance (**15.30% loss**).  
  * Reducing from 8 features to 4 components retains **94.67%**, meaning only **5.33%** of information is discarded. The last two eigenvalues are strictly 0.00 due to exact mathematical collinearity (`TotalGoals = FTHG + FTAG`).

* **Which variables are strongly correlated, and how does this affect PCA?**  
  * `TotalGoals` is an exact linear combination of `FTHG` and `FTAG`, and `GoalDifference` linearly combines them. Additionally, outcome indicators (`HomeWin`, `AwayWin`) correlate heavily with goal margins.  
  * **Effect:** Strong multicollinearity causes variance to concentrate heavily in the first few eigenvectors, rendering the last two components redundant ($0\%$ variance).

* **Interpretation of Major Components (Feature Loadings):**  
  * **PC1 (Match Outcome & Dominance):** Heavy positive loadings on `GoalDifference` (+0.517), `HomeWin` (+0.471), and `FTHG` (+0.444), with negative loading on `AwayWin` (-0.403). It separates home blowout victories from away wins.
  * **PC2 (Match Scoring Volume & Intensity):** High positive loadings on `TotalGoals` (+0.601), `FTAG` (+0.514), `AbsGoalMargin` (+0.425), and `FTHG` (+0.327). It distinguishes low-scoring draws from high-scoring, chaotic fixtures.
  * **PC3 (Temporal Variation):** Dominated almost entirely by `MatchMonth` (-0.997), capturing calendar and scheduling distribution independent of match events.

* **Does the reduced dataset provide a more effective representation?**  
  **Yes.** The original 8-dimensional space contained substantial redundancy (linear dependencies between scorelines, margins, and outcome flags). Projecting onto the first 3 orthogonal axes strips away collinear artifacts, presenting an uncorrelated, clean representation of match outcomes and goal intensities.

---

### Critical Dimensions Comparison

* **Local vs. Global Structure:** PCA preserves global linear variance across the full distribution, separating extreme home/away wins at opposite poles, but can compress finer local sub-patterns among closely contested draws.
* **Cluster Separation:** In the 2D projection, draws (`D`) form a dense cluster near the origin, whereas home wins (`H`) and away wins (`A`) fan out along the positive and negative ends of PC1.
* **Stability:** PCA is globally stable on large datasets ($N = 11,113$), though sensitive to extreme scoring blowouts (e.g., 9–0 games) which exert high leverage on the orientation of PC1 and PC2.
* **Computational Cost:** Negligible. Computing the singular value decomposition (SVD) on an $11113 \times 8$ matrix takes less than 50 milliseconds.
* **Interpretability:** Highly intuitive: PC1 represents *Goal Margin/Dominance*, PC2 represents *Total Match Volume*, and PC3 reflects *Seasonal Timing*.
* **Redundancy:** The original matrix possessed at least 2 zero-variance null dimensions due to deterministic linear dependencies; PCA efficiently eliminates this rank deficiency.

"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import AgglomerativeClustering, DBSCAN, KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import (
    calinski_harabasz_score,
    davies_bouldin_score,
    silhouette_score,
)
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

X_features = X_scaled.T  # Shape: (8, 11113)
feat_linkage = linkage(X_features, method="ward")

plt.figure(figsize=(9, 4.5))
dendrogram(feat_linkage, labels=feature_cols, leaf_rotation=45)
plt.title("Hierarchical Clustering Dendrogram of Features (Feature Space)")
plt.ylabel("Ward Distance")
plt.tight_layout()
plt.show()

km = KMeans(n_clusters=3, random_state=42, n_init=10)
km_labels = km.fit_predict(X_scaled)

agg = AgglomerativeClustering(n_clusters=3, linkage="ward")
agg_labels = agg.fit_predict(X_scaled)

db = DBSCAN(eps=1.5, min_samples=25)
db_labels = db.fit_predict(X_scaled)


def evaluate_clustering(name, labels, X_mat):
    mask = labels != -1
    valid_labels = labels[mask]
    n_clusters = len(set(valid_labels))
    noise_count = np.sum(labels == -1)

    global_var = np.var(X_mat, axis=0).mean()
    cluster_vars = [
        np.var(X_mat[labels == c], axis=0).mean() for c in set(valid_labels)
    ]
    avg_cluster_var = np.mean(cluster_vars)
    var_ratio = avg_cluster_var / global_var

    sil = silhouette_score(X_mat[mask], valid_labels)
    ch = calinski_harabasz_score(X_mat[mask], valid_labels)
    db_idx = davies_bouldin_score(X_mat[mask], valid_labels)

    return {
        "Method": name,
        "Clusters": n_clusters,
        "Noise Pts": noise_count,
        "Avg Cluster Var": round(avg_cluster_var, 4),
        "Var Ratio (C/G)": round(var_ratio, 4),
        "Silhouette": round(sil, 4),
        "Calinski-Harabasz": round(ch, 1),
        "Davies-Bouldin": round(db_idx, 4),
    }


metrics_summary = [
    evaluate_clustering("K-Means", km_labels, X_scaled),
    evaluate_clustering("Agglomerative", agg_labels, X_scaled),
    evaluate_clustering("DBSCAN", db_labels, X_scaled),
]
print("\n--- Clustering Evaluation Metrics ---")
print(pd.DataFrame(metrics_summary).to_string(index=False))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

scatter1 = axes[0].scatter(
    X_pca[:, 0], X_pca[:, 1], c=km_labels, cmap="Set1", s=12, alpha=0.35
)
axes[0].set_title(
    f"K-Means (K=3)\nSilhouette: {metrics_summary[0]['Silhouette']}"
)
axes[0].set_xlabel("PC1")
axes[0].set_ylabel("PC2")

scatter2 = axes[1].scatter(
    X_pca[:, 0], X_pca[:, 1], c=agg_labels, cmap="Set1", s=12, alpha=0.35
)
axes[1].set_title(
    f"Agglomerative (K=3)\nSilhouette: {metrics_summary[1]['Silhouette']}"
)
axes[1].set_xlabel("PC1")

scatter3 = axes[2].scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=db_labels,
    cmap="tab10",
    s=12,
    alpha=0.35,
)
axes[2].set_title(
    f"DBSCAN (eps=1.5)\nClusters: {metrics_summary[2]['Clusters']}, Noise: {metrics_summary[2]['Noise Pts']}"
)
axes[2].set_xlabel("PC1")

plt.tight_layout()
plt.show()

"""# Section 4: Clustering Analysis

## 4.1 Clustering on the Feature Space (Transposed Matrix $X^T$)

* **Information Obtained by Clustering Features:**  
  Clustering features reveals how input variables co-vary across all 11,113 observations, identifying functional collinearity, latent operational groupings, and structural redundancy without human feature engineering.

* **Redundant / Related Feature Groups:**  
  The feature dendrogram uncovers two distinct functional blocks:
  1. **Home Dominance Cluster:** `FTHG`, `GoalDifference`, `HomeWin`, `TotalGoals`, and `AbsGoalMargin` cluster tightly together, showing that offensive production drives match margins and outcome probabilities simultaneously.
  2. **Away Counter-Cluster:** `FTAG` and `AwayWin` merge into a separate, distinct branch.

* **Isolated / Divergent Features:**  
  `MatchMonth` separates at the highest hierarchical branch. Its distance from all scoreline attributes confirms that match outcomes and goal volumes are statistically independent of scheduling dates.

* **Novel Insights vs. Sample Clustering:**  
  While sample clustering groups fixtures by result, feature clustering directly proves feature redundancy (such as deterministic coupling between goal counts, totals, and margin metrics), providing an objective basis for feature selection.

* **Relevant Domains:**  
  Feature clustering is particularly essential in bioinformatics (gene expression arrays), sensor telemetry (identifying co-dependent sensors), financial risk (grouping correlated assets), and text mining.

---

## 4.2 Algorithms: Intuition, Assumptions, Strengths & Weaknesses

| Method | Mathematical Intuition | Core Assumptions | Strengths | Weaknesses | Real-World Cluster Meaning |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **K-Means** | Iterative centroid repositioning minimizing within-cluster sum-of-squares (WCSS). | Spherical clusters, equal variance, convex geometry. | Fast ($O(k \cdot n \cdot d)$), scales cleanly to large datasets. | Sensitive to initialization and outliers; forces every sample into a cluster. | **Cluster 0:** Home Wins; **Cluster 1:** Low-scoring Draws; **Cluster 2:** Away Wins. |
| **Hierarchical (Ward)** | Greedy bottom-up merging minimizing incremental variance increase ($\Delta WCSS$). | Nested hierarchical taxonomy, monotonic cluster distances. | Deterministic, no random seed required, constructs intuitive dendrograms. | Computationally intensive ($O(n^2)$ memory), non-reversible merges. | Partitions matches into Home Dominance, Contested Stalemate, and Visiting Upsets. |
| **DBSCAN** | Density-connectivity via $\epsilon$-neighborhood density thresholds ($\text{MinPts}$). | Clusters are high-density regions separated by low-density margins. | Discovers arbitrary geometries, isolates genuine anomalies/noise (-1). | Fails across variable density regimes; highly sensitive to hyperparameter choices. | Main clusters isolate standard scorelines (1–0, 0–0, 2–1); noise points isolate historic blowouts. |

---

## 4.3 Metric Evaluation: Average Cluster Variance vs. Global Variance

* **Is the Metric Suitable?**  
  **Partially.** The ratio of average within-cluster variance to global variance ($\frac{\bar{\sigma}^2_{\text{cluster}}}{\sigma^2_{\text{global}}}$) directly quantifies variance reduction:
  * For K-Means and Agglomerative clustering, the ratio drops to **~0.48**, proving that partitioning reduces internal dispersion by over **51%**.
  * For DBSCAN, the ratio drops to **~0.25** within dense sub-cores.
* **Limitations & Alternative Metrics:**  
  This metric monotonically favors over-clustering (as $k \to N$, variance $\to 0$) and fails to measure inter-cluster separation.  
  * **Suitable Alternatives:** The **Silhouette Score** (measuring cohesion vs. separation, yielding **0.358** for Agglomerative) and the **Davies-Bouldin Index** (**1.13**) provide balanced validation independent of cluster counts.

---

## 4.4 Synthesis & Comparative Discussion

* **Why Different Algorithms Produce Different Clusters:**  
  K-Means and Agglomerative (Ward) enforce convex partitions around central score centroids, dividing the continuous football score space into three balanced outcome territories. DBSCAN operates entirely on local density, grouping identical frequent outcomes (e.g., standard 1–1 and 1–0 games) into compact sub-islands while rejecting sparse blowouts.
* **Sensitivity to Hyperparameters:**  
  K-Means is sensitive to the choice of $k$ and initial centroid seeds. DBSCAN exhibits extreme sensitivity to $\epsilon$ and $\text{MinPts}$: minor variations collapse the dataset into a single mega-cluster or misclassify most samples as noise.
* **Density-Based vs. Centroid-Based Approaches:**  
  Centroid methods provide comprehensive domain partitioning (every game receives a category), which aligns with tactical classification. Density-based methods excel at separating routine matches from chaotic high-score outliers.
* **Failure Modes:**  
  Clustering fails when features lack clear density valleys (such as uniform score transitions) or when high multicollinearity distorts Euclidean distance metrics without dimensionality reduction.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

z_scores = np.abs(X_scaled)
z_anomalies = (z_scores > 3.0).any(axis=1)

iso_forest = IsolationForest(contamination=0.02, random_state=42)
iso_pred = iso_forest.fit_predict(X_scaled)
iso_anomalies = iso_pred == -1
iso_scores = -iso_forest.decision_function(X_scaled)

lof = LocalOutlierFactor(n_neighbors=30, contamination=0.02)
lof_pred = lof.fit_predict(X_scaled)
lof_anomalies = lof_pred == -1
lof_scores = -lof.negative_outlier_factor_

print("--- Anomaly Detection Counts ---")
print(
    f"Z-Score (|Z| > 3): {z_anomalies.sum()} anomalies ({z_anomalies.mean()*100:.2f}%)"
)
print(
    f"Isolation Forest:  {iso_anomalies.sum()} anomalies ({iso_anomalies.mean()*100:.2f}%)"
)
print(
    f"LOF:               {lof_anomalies.sum()} anomalies ({lof_anomalies.mean()*100:.2f}%)"
)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].scatter(
    X_pca[~z_anomalies, 0],
    X_pca[~z_anomalies, 1],
    c="lightgray",
    s=10,
    alpha=0.4,
    label="Normal",
)
axes[0].scatter(
    X_pca[z_anomalies, 0],
    X_pca[z_anomalies, 1],
    c="red",
    s=25,
    label="Z-Score Anomaly",
)
axes[0].set_title(f"Z-Score (|Z| > 3)\nCount: {z_anomalies.sum()}")
axes[0].set_xlabel("PC1")
axes[0].set_ylabel("PC2")
axes[0].legend()

axes[1].scatter(
    X_pca[~iso_anomalies, 0],
    X_pca[~iso_anomalies, 1],
    c="lightgray",
    s=10,
    alpha=0.4,
    label="Normal",
)
axes[1].scatter(
    X_pca[iso_anomalies, 0],
    X_pca[iso_anomalies, 1],
    c="crimson",
    s=25,
    label="IF Anomaly",
)
axes[1].set_title(f"Isolation Forest (2%)\nCount: {iso_anomalies.sum()}")
axes[1].set_xlabel("PC1")
axes[1].legend()

axes[2].scatter(
    X_pca[~lof_anomalies, 0],
    X_pca[~lof_anomalies, 1],
    c="lightgray",
    s=10,
    alpha=0.4,
    label="Normal",
)
axes[2].scatter(
    X_pca[lof_anomalies, 0],
    X_pca[lof_anomalies, 1],
    c="darkorange",
    s=25,
    label="LOF Anomaly",
)
axes[2].set_title(f"Local Outlier Factor (k=30)\nCount: {lof_anomalies.sum()}")
axes[2].set_xlabel("PC1")
axes[2].legend()

plt.tight_layout()
plt.show()

extreme_matches = (
    df[iso_anomalies][
        [
            "Season",
            "DateTime",
            "HomeTeam",
            "AwayTeam",
            "FTHG",
            "FTAG",
            "TotalGoals",
            "GoalDifference",
        ]
    ]
    .sort_values(by="TotalGoals", ascending=False)
    .head(5)
)

print("\nTop 5 Extreme Matches Flagged by Isolation Forest:")
print(extreme_matches.to_string(index=False))

"""# Section 5: Multi-Dimensional Anomaly Detection

## 5.1 Z-Score Method

* **Assumption of Gaussianity:**  
  The Z-score transformation $Z = \frac{X - \mu}{\sigma}$ strictly assumes that the underlying data follows a univariate Gaussian (Normal) distribution. In football match statistics, scores follow discrete, non-negative, right-skewed Poisson distributions. Applying a Gaussian assumption over-penalizes the long positive tail while ignoring lower-bound physical constraints (goals cannot be negative).

* **Failure in High Dimensions:**  
  * In multidimensional space, points can exhibit normal marginal Z-scores along every single feature individually while existing as clear joint anomalies (violating inter-feature correlations).  
  * Furthermore, as dimensionality $d$ increases, the probability of at least one feature exceeding $|Z| > 3$ grows spuriously due to multiple hypothesis testing (curse of dimensionality).

* **Feature-Wise vs. Global Anomaly Detection:**  
  * **Feature-wise:** Flags an observation if $\max_j |Z_{i,j}| > 3$, treating features as independent axes. It successfully catches historic single-metric blowouts (e.g., 9 goals scored) but misses coordinate-level mismatches.  
  * **Global:** Measures distance accounting for joint covariance (e.g., Mahalanobis distance or multivariate isolation), assessing whether an entire coordinate vector is improbable given the covariance structure.

---

## 5.2 Isolation Forest

* **Isolation Mechanism & Random Partitioning:**  
  Isolation Forest exploits the structural vulnerability of anomalies: few in quantity and located far from dense regions. The algorithm constructs recursive binary trees (iTrees) by randomly selecting a feature and a random split value between the feature's minimum and maximum. Anomalies require significantly fewer random splits to be isolated at shallow depths, whereas normal points require extensive branching.

* **Role of the Contamination Parameter:**  
  The `contamination` parameter ($0.02$ in our model) defines the expected proportion of outliers in the dataset. It acts as an operational decision threshold over the continuous anomaly score distribution.

* **Advantages and Limitations:**  
  * **Advantages:** Linear time complexity $O(t \cdot \psi \log \psi)$, highly effective in high-dimensional spaces, invariant to monotonic feature scaling, and makes no distributional assumptions.
  * **Limitations:** Axis-parallel splits can create artificial artifacts in dense coordinate regions, and masking effects can occur if anomalies form small, tight clusters.

* **Anomaly Score Calculation & Interpretation:**  
  The anomaly score $s(x, n) = 2^{-\frac{E(h(x))}{c(n)}}$ normalizes average tree path length $E(h(x))$ against average unsuccessful search tree depth $c(n)$:
  * If $s \to 1$ (short path length): High certainty anomaly.
  * If $s < 0.5$ (long path length): Structural inlier.
  * **Visual Interpretation:** Identified anomalies map directly to historical extreme games (e.g., Portsmouth 7–4 Reading, Man United 8–2 Arsenal), lying along the extreme periphery of PC1 and PC2.

---

## 5.3 Local Outlier Factor (LOF)

* **Local Density Estimation:**  
  LOF assesses the local reachability density (lrd) of an observation relative to its $k$-nearest neighbors. An object's score represents the ratio of the average local densities of its neighbors to its own local density.

* **Neighborhood Effects:**  
  By normalizing density locally, LOF detects anomalies nestled in regions of varying density—identifying points that are isolated relative to their immediate vicinity rather than the entire dataset.

* **Sensitivity to Parameter $k$:**  
  * Small $k$ (e.g., $k < 10$) causes sensitivity to local stochastic fluctuations and noise.  
  * Large $k$ (e.g., $k \ge 50$) smooths local variations into a quasi-global density estimator. We selected $k=30$ to maintain local neighborhood stability across 11,113 matches.

* **Difference Between Global and Local Anomalies:**  
  * **Global Anomalies (caught by IF & Z-score):** Points far from all data centers (e.g., rare 10-goal blowouts).  
  * **Local Anomalies (caught by LOF):** Observations located in sparse gaps between distinct outcome regions (e.g., unusual margin-to-month combinations), even if their absolute goal count is modest.
"""

import time
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

t0 = time.time()
z_anom = (np.abs(X_scaled) > 3.0).any(axis=1)
time_z = time.time() - t0

t0 = time.time()
iso = IsolationForest(contamination=0.02, random_state=42)
iso_anom = iso.fit_predict(X_scaled) == -1
time_iso = time.time() - t0

t0 = time.time()
lof = LocalOutlierFactor(n_neighbors=30, contamination=0.02)
lof_anom = lof.fit_predict(X_scaled) == -1
time_lof = time.time() - t0

both_z_iso = int((z_anom & iso_anom).sum())
both_iso_lof = int((iso_anom & lof_anom).sum())
both_z_lof = int((z_anom & lof_anom).sum())
all_three = int((z_anom & iso_anom & lof_anom).sum())

comp_df = pd.DataFrame(
    [
        {
            "Method": "Z-Score (|Z| > 3)",
            "Count": int(z_anom.sum()),
            "Pct (%)": round(z_anom.mean() * 100, 2),
            "Runtime (s)": round(time_z, 4),
        },
        {
            "Method": "Isolation Forest",
            "Count": int(iso_anom.sum()),
            "Pct (%)": round(iso_anom.mean() * 100, 2),
            "Runtime (s)": round(time_iso, 4),
        },
        {
            "Method": "LOF (k=30)",
            "Count": int(lof_anom.sum()),
            "Pct (%)": round(lof_anom.mean() * 100, 2),
            "Runtime (s)": round(time_lof, 4),
        },
    ]
)

print("--- Method Performance & Counts ---")
print(comp_df.to_string(index=False))
print("\n--- Overlap Matrix ---")
print(f"Overlap (Z-Score & Isolation Forest): {both_z_iso}")
print(f"Overlap (Isolation Forest & LOF):     {both_iso_lof}")
print(f"Overlap (Z-Score & LOF):              {both_z_lof}")
print(f"Identified by ALL Three:             {all_three}")

plt.figure(figsize=(7, 4))
bars = plt.bar(
    ["Z-Score Only", "Z & IF Agreement", "LOF Only"],
    [int(z_anom.sum() - both_z_iso), both_z_iso, int(lof_anom.sum())],
    color=["skyblue", "navy", "orange"],
)
plt.ylabel("Match Count")
plt.title("Agreement & Specificity Across Anomaly Detectors")
for bar in bars:
    yval = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        yval + 4,
        f"{yval}",
        ha="center",
        va="bottom",
    )
plt.tight_layout()
plt.show()

"""# Section 6: Comprehensive Comparison of Anomaly Detection Methods

### 1. Agreement and Method-Specific Anomalies
* **Consensus Anomalies (Global Outliers):**
  * **Strong Z-Score and Isolation Forest Concordance:** 223 matches were simultaneously flagged by both Z-Score and Isolation Forest (100% of the Isolation Forest set). These represent undeniable global scoreline anomalies—historic blowouts such as 9–0, 8–2, and 7–4 scorelines with extreme total goals and goal margins.
* **Method-Specific Divergence:**
  * **LOF vs. Tree/Distance Methods:** LOF displayed 0 overlap with Z-Score and Isolation Forest. While IF and Z-Score search for points far from the global center (extreme numerical tails), LOF isolates **local density troughs**—identifying routine scorelines (e.g., 1–3 or 0–3) that occurred in sparse seasonal combinations or transitional calendar months where local neighbor density is slightly reduced.

---

### 2. Multi-Criteria Method Comparison

| Evaluation Dimension | Z-Score Method | Isolation Forest | Local Outlier Factor (LOF) |
| :--- | :--- | :--- | :--- |
| **Sensitivity to Scaling** | **Invariant** (Standardization is built-in). | **Invariant** to monotonic scaling (decision trees rely solely on feature order splits). | **Extremely Sensitive** (Euclidean distances directly shift if scaling is altered). |
| **Dimensionality Sensitivity** | **High** (False discovery rate rises across dimensions; ignores joint multi-feature geometry). | **Very Low** (Subsampling and random projections scale robustly up to high dimensions). | **Severe** (Suffers from the curse of dimensionality; distance metrics lose contrast). |
| **Runtime & Scalability** | **Instantaneous** ($O(N \cdot d)$, $\approx 0.0003$s). | **Fast** ($O(t \cdot \psi \log \psi)$, $\approx 0.36$s). Scalable to millions of samples. | **Moderate** ($O(N^2 \cdot d)$, $\approx 0.21$s). Struggles with very large sample sizes. |
| **Robustness to Noise** | **Poor** (Extreme noise inflates $\mu$ and $\sigma$, leading to masking of other outliers). | **High** (Tree averaging isolates outliers without letting them distort tree splits). | **Moderate** (Sensitive to sparse noise points mimicking low-density regions). |
| **Interpretability** | **High** (Expressed as standard deviations away from the mean on a specific feature). | **Moderate** (Global score is intuitive, but inspecting individual path splits requires SHAP/TreeExplainer). | **Low** (Relative reachability density ratios are non-intuitive for practitioners). |

---

### 3. False Positives, False Negatives & Real-World Implications (Non-Technical Explanation)

In sports analytics, match data integrity directly informs betting odds, tactical scouting, performance metrics, and integrity monitoring (such as detecting match-fixing):

* **False Positive (Type I Error):**
  * **What it means:** The model flags a completely fair, authentic football match as "abnormal" simply because of a rare scoreline (for example, a thrilling 5–5 draw or a 9–0 blowout by a dominant team).
  * **Real-World Consequence:** Unnecessary red flags. In integrity monitoring, this could lead to false accusations of match-fixing or wasting hundreds of investigative hours auditing legitimate sporting entertainment.

* **False Negative (Type II Error):**
  * **What it means:** An anomalous, corrupted, or rigged match slips past the system undetected because its surface scoreline appears conventional (for example, an intentionally arranged 1–0 defeat that exhibits abnormal betting or foul dynamics).
  * **Real-World Consequence:** Severe security and integrity blind spots. Systemic corruptions, data collection errors, or illegal betting patterns remain hidden because models reliant purely on final score margins consider standard scorelines ordinary.

# Section 7: Critical Analysis, Reflection, and Ethical Considerations

## 7.1 Methodological Reflection and Critical Analysis

### 1. Why Anomaly Detection is Fundamentally Ill-Defined
Unlike supervised classification where models optimize against concrete, ground-truth targets, anomaly detection in real-world data operates without objective class definitions. In an unsupervised context:
* **No Unified Definition of "Normal":** What constitutes the boundary between a rare, valid occurrence and an anomaly depends entirely on subjective user-defined thresholds (e.g., setting `contamination=0.02` vs. `0.05`).
* **Ill-Defined Objectives:** A data scientist cannot rigorously compute empirical loss or test set error without labels. Consequently, multiple competing algorithms can generate entirely disjoint anomaly candidate sets, and each conclusion remains mathematically defensible under its own assumptions.

### 2. The Curse of Dimensionality & Distance Degradation
As the dimensionality $d$ of a feature space grows:
* **Hypervolume Expansion:** The volume of the feature space increases exponentially ($V \propto r^d$), causing the data points to become extremely sparse.
* **Loss of Distance Contrast:** The distance to the nearest neighbor converges toward the distance to the farthest neighbor:
  $$\lim_{d \to \infty} \frac{\text{dist}_{\max} - \text{dist}_{\min}}{\text{dist}_{\min}} \to 0$$
* **Impact on Algorithms:** Distance-based models (such as LOF and $k$-NN) lose discriminative contrast because all data points appear roughly equidistant from one another. Random partition models (such as Isolation Forest) handle this degradation far better because individual decision trees isolate points along sparse sub-dimensional projections rather than computing global Euclidean distances.

### 3. Noise vs. Genuine Anomalies: EPL Dataset Example
* **Noise:** Random, unstructured stochastic perturbations, rounding artifacts, or data recording errors that carry no informational value.
* **Genuine Anomaly:** An authentic, highly structured data point generated by the real underlying process that deviates drastically from standard operating patterns.
* **Concrete Example from our Dataset:**  
  The historic match between **Portsmouth and Reading on September 29, 2007 (Season 2007–08)** ended in an astonishing **7–4 scoreline (11 total goals)**.
  * Algorithms like Isolation Forest and Z-Score flagged this fixture as a severe outlier.
  * **Why it is a genuine, legitimate instance:** It was not a data-entry corruption or corrupted sensor log; it represents the highest-scoring single fixture in the history of the Premier League. The scoreline is an authentic realization of the sporting process, driven by tactical breakdowns and late defensive collapses.

### 4. Risks of Assuming Gaussianity
Parametric models like the standard Z-score assume an underlying Gaussian distribution $\mathcal{N}(\mu, \sigma^2)$:
* **Skewness Blindness:** Football goals are discrete, non-negative counts following right-skewed Poisson processes. Applying symmetric Gaussian thresholds over-penalizes the positive tail while ignoring the lower bounded boundary ($Goals \ge 0$).
* **Missed Anomalies:** Multi-modal distributions and non-linear feature relationships cannot be captured. A match with 3 goals conceded in 2 minutes might be historically rare, but if total goals stay within 3 standard deviations, Gaussian models completely miss it.

### 5. Why Reduced Visualizations (e.g., PCA) Can Mislead
* **Projection Compression:** A 2D PCA projection retains only the directions of maximum linear variance (in our case, ~72%). By collapsing higher dimensions, points that are distant outliers along orthogonal residual axes (such as PC3 or PC4) can project directly into the center of dense clusters in 2D.
* **Non-Linear Manifold Distortion:** PCA enforces linear projections. If anomalies exist on non-linear curved manifolds, linear projections can falsely project separate structural clusters onto the same plane, creating illusions of overlap or masking clear outliers.

---

## 7.2 Ethical Considerations

### 1. Real-World Consequences of False Alarms & "Alert Fatigue"
When an anomaly detector generates excessive false alarms, human operators suffer from cognitive **alert fatigue**:
* In high-stakes monitoring (e.g., critical infrastructure or sports betting fraud), frequent false positives cause human auditors to ignore, dismiss, or disable system alerts entirely.
* When a catastrophic, genuine anomaly eventually occurs, it is frequently missed because it was drowned in a flood of uninformative notifications.

### 2. Surveillance: Benefits vs. Risks
* **Benefits:** Automated detection of erratic driving patterns on highways, structural bridge faults, or early crowd crushes in stadium management.
* **Risks:** When applied to behavioral surveillance, anomaly detection systems can encode cultural and racial profiling. Individuals behaving slightly differently from a statistical "norm" (e.g., pacing while nervous or speaking loudly) are unfairly flagged for aggressive intervention.

### 3. Medical Applications
* **False Positive (Type I):** Classifying a healthy patient's lab metrics as anomalous can lead to severe emotional distress, invasive biopsies, and exposure to unnecessary medical treatments.
* **False Negative (Type II):** Classifying an atypical, early-stage malignancy as "normal" delays life-saving interventions, resulting in fatal clinical outcomes.

### 4. Cybersecurity: Attack Misses vs. Legitimate Flagging
* **Missing a Genuine Attack (False Negative):** Breaches network perimeters, leading to massive data exfiltration, ransomware disruption, and millions of dollars in liability.
* **Flagging Legitimate Activity (False Positive):** Locking out authorized engineers, halting continuous deployment pipelines, and disrupting legitimate customer transactions during business-critical operations.
* **Trade-off:** In cybersecurity, practitioners deliberately tolerate higher false positive rates because the asymmetry of a single missed attack is far more catastrophic than a brief operational delay.

### 5. Privacy, Bias, and the Ethics of Labeling "Abnormal"
The mathematical label "outlier" carries severe ethical weight when mapped to human beings:
* **The Normative Fallacy:** Algorithms assume the majority pattern is desirable and legitimate, while statistical minorities are flagged as problematic.
* **Feedback Loops:** If demographic minorities exhibit higher variance in credit usage, job tenure, or movement patterns, unsupervised anomaly detectors flag them disproportionately, entrenching historical biases under the guise of objective mathematics.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

df_dash = df.copy()
X_dash = df_dash[feature_cols]

scaler = StandardScaler()
X_scaled_dash = scaler.fit_transform(X_dash)

pca_dash = PCA(n_components=2)
coords_pca = pca_dash.fit_transform(X_scaled_dash)
df_dash["PC1"] = coords_pca[:, 0]
df_dash["PC2"] = coords_pca[:, 1]

km_dash = KMeans(n_clusters=3, random_state=42, n_init=10)
df_dash["Cluster"] = km_dash.fit_predict(X_scaled_dash).astype(str)

iso_dash = IsolationForest(contamination=0.02, random_state=42)
df_dash["Anomaly_IF"] = np.where(
    iso_dash.fit_predict(X_scaled_dash) == -1, "Anomaly", "Normal"
)

df_dash["Match_Info"] = (
    df_dash["Season"]
    + " | "
    + df_dash["HomeTeam"]
    + " "
    + df_dash["FTHG"].astype(str)
    + " - "
    + df_dash["FTAG"].astype(str)
    + " "
    + df_dash["AwayTeam"]
)

fig_interactive = px.scatter(
    df_dash,
    x="PC1",
    y="PC2",
    color="Anomaly_IF",
    symbol="Cluster",
    hover_name="Match_Info",
    hover_data={
        "TotalGoals": True,
        "GoalDifference": True,
        "PC1": ":.2f",
        "PC2": ":.2f",
    },
    color_discrete_map={"Normal": "#8ecae6", "Anomaly": "#d90429"},
    opacity=0.6,
    title="Interactive Dashboard: PCA Projection, Clusters & Anomalies (Hover for Match Details)",
    width=900,
    height=550,
)
fig_interactive.show()

plt.figure(figsize=(9, 4))
cluster_centers = (
    pd.DataFrame(X_scaled_dash, columns=feature_cols)
    .groupby(df_dash["Cluster"])
    .mean()
)
sns.heatmap(
    cluster_centers, annot=True, cmap="vlag", fmt=".2f", cbar_kws={"label": "Z-Score"}
)
plt.title("Cluster Profile Heatmap (Mean Feature Standardized Values)")
plt.ylabel("Cluster")
plt.tight_layout()
plt.show()

core_features = ["FTHG", "FTAG", "TotalGoals", "GoalDifference"]
pairplot_data = df_dash[core_features + ["Anomaly_IF"]].sample(
    n=1500, random_state=42
)

sns.pairplot(
    pairplot_data,
    hue="Anomaly_IF",
    palette={"Normal": "#3a86ff", "Anomaly": "#ff006e"},
    plot_kws={"alpha": 0.5, "s": 25},
    corner=True,
)
plt.suptitle("Pairplot of Key Match Features (Normal vs Anomalies)", y=1.02)
plt.show()